/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DoctorHealthBlock } from "./DoctorHealthBlock";
export type { HealthBlock } from "./HealthBlock";
export * as factories from "./factories";
export { DoctorHealthBlock__factory } from "./factories/DoctorHealthBlock__factory";
export { HealthBlock__factory } from "./factories/HealthBlock__factory";
