/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HCProviderHealthBlock } from "./HCProviderHealthBlock";
export type { HealthBlock } from "./HealthBlock";
export * as factories from "./factories";
export { HCProviderHealthBlock__factory } from "./factories/HCProviderHealthBlock__factory";
export { HealthBlock__factory } from "./factories/HealthBlock__factory";
