/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HealthBlock__factory } from "./HealthBlock__factory";
export { PatientProvider__factory } from "./PatientProvider__factory";
